spring:
  application:
    name: unit-and-resolve-service
  r2dbc:
    url: r2dbc:postgresql://localhost/unit-and-resolve
    username: postgres
    password: 12345
  liquibase:
    url: jdbc:postgresql://localhost/unit-and-resolve
    user: postgres
    password: 12345
  mail:
    host: smtp.gmail.com
    port: 587
    username: common.usercreation@gmail.com
    password: culusfiikfawsnqh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8001
  error:
    include-message: always
